### ISSUE TITLE
1. Update bathy file

### ISSUE THREAD

**Issue by jpolton** [JMMP-Group/CO_AMM15#24]
Enda merging and testing options.

Will alert all when new bathymetry is settled.

**Comment by jpolton** [comment]
@endaodea to choose between pure GEBCO or EMODNET data, and not look back...

**Comment by jpolton** [comment]
Enda said:

"No pre-smoothing has been applied yet which is likely to be a small overall effect though may have some HPG implications.
Also are straight from interpolation of SRC bathy rather then box meaning, though box meaning version didn't produce huge differences.

Will look int Mike's prefilter , it requires having N iterations * M order of filter extra points around the domain to be smoothed and thus needs a wider coordinates file to go with it and them make a final cut out into the AMM15 domain."

**Comment by endaodea** [comment]
Have created a test pre-smoothed bathy  and config file for SF12 case. 
available on Jamsin: jmmp_collab/AMM15/GATHER_EXPERIMENTAL_EMODNET_GEBCO_DOMAIN_CFG

**Comment by jpolton** [comment]
@endaodea will add in the Baltic Mods from Nico

**Comment by endaodea** [comment]
* 2D tidal experiments with Emodnet-Gebco-Emodnet completed suggest this is the best set of bathy to go with.
* LSM is imposed to be exactly that of the current operational bathy, scope to improve but not on this round
* Tested with pre-smoothing but that resulted in significantly deteriorated tides.
* Have also replicated Nico's 0.1 rmax smoothing in the baltic region (no ill effects)
* Directly applied Nicos Baltic boundary condition bathy on the bdy itself
  * This requires explicit copying in a bathy of unknown origin (Nicos) which is less than ideal


There is scope for improvement with Emodnet right out to the coast but the G-E-G is ready to go

The G-E-G bathy actually does not have any points that are Negative (though some are close to zero).
This would mean no special treatment is needed for WAD for initial/bdy conditions.
However we want a general solution in place to cover the case where negative bathy is present which would be the case if we used pure EMODNET

(We found another gotcha for that case, we think we have a solution)

Next stage is to set up 3D test case with new bathy to see if any issues in 3D.
There after set up ME case. (probably  a combo of Enda with Diegos advice )

Note Also found adding Lateral no slip bdy significantly improves tide but 
has a problematic point near a river in a 1 point estuary near Sweden. Could potentially edit this river point/estuary.

**Comment by endaodea** [comment]
Bathy File update
Wrote supporting documentation about how it was genearted in branch under review to be merged.

Note main points are:

* Merge GEBCO and EMODNET 
* Took GEBCO for DEEP EMODNET for shallow (except WAD, where GEBCO is still used)
* "corrected LAT" using Surge model as before
* Made all rivers points have a min depth of 10m for W&D stability
* Spliced on Dave's Baltic bathy effectively imposing rmax here directly on bathy to prevent saw toothing
